packages:
  - apps/*
  - packages/*

catalog:
  eslint: ^9.10.0
  prettier: ^3.3.3
  typescript: ^5.6.2
  zod: ^3.23.8
  tailwindcss: ^3.4.12
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": ^18.3.8
  "@types/react-dom": ^18.3.0
  "@types/node": ^22.5.5
  "@kyh/eslint-config": ^1.0.6
  "@kyh/prettier-config": ^1.0.6
  "@kyh/tsconfig": ^1.0.6
  "@tanstack/react-query": ^5.56.2
  "@tanstack/react-query-devtools": ^5.56.2
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
