packages:
  - apps/*
  - packages/*

catalog:
  eslint: ^9.9.1
  prettier: ^3.3.3
  typescript: ^5.5.4
  zod: ^3.23.8
  tailwindcss: ^3.4.10
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": ^18.3.5
  "@types/react-dom": ^18.3.0
  "@types/node": ^22.5.4
  "@kyh/eslint-config": ^1.0.4
  "@kyh/prettier-config": ^1.0.4
  "@kyh/tsconfig": ^1.0.4
  "@tanstack/react-query": ^5.54.1
  "@tanstack/react-query-devtools": ^5.54.1
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
