packages:
  - apps/*
  - packages/*

catalog:
  # Dev tooling
  "@kyh/eslint-config": ^1.1.4
  "@kyh/prettier-config": ^1.1.4
  "@kyh/tsconfig": ^1.1.4
  "@types/node": ^22.13.10
  "@types/react-dom": ^19.0.4
  "@types/react": ^19.0.10
  "eslint": ^9.22.0
  "prettier": ^3.5.3
  "typescript": ^5.8.2

  # API
  "@tanstack/react-query": ^5.67.1
  "@trpc/client": ^11.0.0-rc.824
  "@trpc/tanstack-react-query": ^11.0.0-rc.824
  "@trpc/server": ^11.0.0-rc.824

  # Misc
  "superjson": "2.2.2"
  "zod": ^3.24.2

  # Client
  "next": ^15.2.1
  "react-dom": ^19.0.0
  "react": ^19.0.0
