packages:
  - apps/*
  - packages/*

catalog:
  # Dev tooling
  "@kyh/eslint-config": ^1.1.4
  "@kyh/prettier-config": ^1.1.4
  "@kyh/tsconfig": ^1.1.4
  "@types/node": ^22.14.0
  "@types/react-dom": ^19.1.2
  "@types/react": ^19.1.0
  "eslint": ^9.24.0
  "prettier": ^3.5.3
  "typescript": ^5.8.3

  # API
  "@tanstack/react-query": ^5.72.2
  "@trpc/client": ^11.0.4
  "@trpc/tanstack-react-query": ^11.0.4
  "@trpc/server": ^11.0.4

  # Misc
  "superjson": "2.2.2"
  "zod": ^3.24.2

  # Client
  "vite": "^6.2.5"
  "next": ^15.3.0
  "react-dom": ^19.1.0
  "react": ^19.1.0
