packages:
  - apps/*
  - packages/*

catalog:
  # Dev tooling
  "@kyh/eslint-config": ^1.1.5
  "@kyh/prettier-config": ^1.1.5
  "@kyh/tsconfig": ^1.1.5
  "@types/node": ^22.15.17
  "@types/react-dom": ^19.1.3
  "@types/react": ^19.1.3
  "eslint": ^9.26.0
  "prettier": ^3.5.3
  "typescript": ^5.8.3

  # API
  "@tanstack/react-query": ^5.75.7
  "@trpc/client": ^11.1.2
  "@trpc/tanstack-react-query": ^11.1.2
  "@trpc/server": ^11.1.2

  # Misc
  "superjson": "2.2.2"
  "zod": ^3.24.4

  # Client
  "next": ^15.3.2
  "react-dom": ^19.1.0
  "react": ^19.1.0
  "vite": "^6.3.5"
