packages:
  - apps/*
  - packages/*

catalog:
  # Dev tooling
  "@kyh/eslint-config": ^1.1.4
  "@kyh/prettier-config": ^1.1.4
  "@kyh/tsconfig": ^1.1.4
  "@types/node": ^22.14.1
  "@types/react-dom": ^19.1.2
  "@types/react": ^19.1.2
  "eslint": ^9.25.0
  "prettier": ^3.5.3
  "typescript": ^5.8.3

  # API
  "@tanstack/react-query": ^5.74.4
  "@trpc/client": ^11.1.0
  "@trpc/tanstack-react-query": ^11.1.0
  "@trpc/server": ^11.1.0

  # Misc
  "superjson": "2.2.2"
  "zod": ^3.24.3

  # Client
  "next": ^15.3.1
  "react-dom": ^19.1.0
  "react": ^19.1.0
  "vite": "^6.3.2"
