packages:
  - apps/*
  - packages/*

catalog:
  eslint: ^9.13.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  zod: ^3.23.8
  tailwindcss: ^3.4.14
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  "@types/node": ^22.8.0
  "@kyh/eslint-config": ^1.0.9
  "@kyh/prettier-config": ^1.0.9
  "@kyh/tsconfig": ^1.0.9
  "@tanstack/react-query": ^5.59.16
  "@tanstack/react-query-devtools": ^5.59.16
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
