packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.2
  "@kyh/prettier-config": ^1.1.2
  "@kyh/tsconfig": ^1.1.2
  "@tanstack/react-query-devtools": ^5.62.7
  "@tanstack/react-query": ^5.62.7
  "@trpc/client": ^11.0.0-rc.593
  "@trpc/react-query": ^11.0.0-rc.593
  "@trpc/server": ^11.0.0-rc.593
  "@types/node": ^22.10.2
  "@types/react-dom": ^18.3.1
  "@types/react": ^18.3.12
  "eslint": ^9.16.0
  "next": ^15.1.0
  "prettier": ^3.4.2
  "react-dom": ^18.3.1
  "react": ^18.3.1
  "tailwindcss": ^3.4.16
  "typescript": ^5.7.2
  "zod": ^3.24.1
