packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.7
  "@kyh/prettier-config": ^1.1.7
  "@kyh/tsconfig": ^1.1.7
  "@tanstack/react-query": ^5.85.5
  "@trpc/client": ^11.5.0
  "@trpc/server": ^11.5.0
  "@trpc/tanstack-react-query": ^11.5.0
  "@types/node": ^24.3.0
  "@types/react": ^19.1.11
  "@types/react-dom": ^19.1.7
  eslint: ^9.34.0
  next: ^15.5.0
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  superjson: ^2.2.2
  typescript: ^5.9.2
  vite: ^7.1.3
  zod: ^4.0.17
