packages:
  - apps/*
  - packages/*

catalog:
  "@kyh/eslint-config": ^1.1.7
  "@kyh/prettier-config": ^1.1.7
  "@kyh/tsconfig": ^1.1.7
  "@tanstack/react-query": ^5.83.0
  "@trpc/client": ^11.4.3
  "@trpc/server": ^11.4.3
  "@trpc/tanstack-react-query": ^11.4.3
  "@types/node": ^24.1.0
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  eslint: ^9.31.0
  next: ^15.4.3
  prettier: ^3.6.2
  react: ^19.1.0
  react-dom: ^19.1.0
  superjson: ^2.2.2
  typescript: ^5.8.3
  vite: ^7.0.5
  zod: ^3.25.76
