services:
  - type: web
    name: playhouse-client
    env: static
    branch: render
    buildCommand: cd client && npm i && npm run build
    staticPublishPath: client/build
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: playhouse-server
    env: elixir
    branch: render
    buildCommand: cd server && ./build.sh
    startCommand: cd server && _build/prod/rel/playhouse/bin/playhouse start
    autoDeploy: true
