import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const carbonFont = localFont({
  src: "./fonts/carbon.woff2",
  display: "swap",
  variable: "--font-carbon",
});

const robotoFont = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${carbonFont.variable} ${robotoFont.variable} font-mono`}
      >
        {children}
      </body>
    </html>
  );
}
