import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localFont from "next/font/local";

import DiscoverIcon from "@/public/icons/discover.svg";
import HeartIcon from "@/public/icons/heart.svg";
import LogoIcon from "@/public/icons/logo.svg";
import PlayIcon from "@/public/icons/play.svg";

import "./globals.css";

import { IconButton } from "./components/ui/icon-button";

const carbonFont = localFont({
  src: "./fonts/carbon.woff2",
  display: "swap",
  variable: "--font-carbon",
});

const robotoFont = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${carbonFont.variable} ${robotoFont.variable} font-mono`}
      >
        <div className="flex min-h-screen w-full">
          <div className="bg-normal flex w-full max-w-[120px] flex-col gap-20 p-10">
            <LogoIcon />
            <div className="flex flex-col gap-14">
              <IconButton variant="transparent" icon={<DiscoverIcon />} />
              <IconButton variant="transparent" icon={<PlayIcon />} />
              <IconButton variant="transparent" icon={<HeartIcon />} />
            </div>
          </div>

          <div className="flex w-full justify-center bg-gray-50">
            <div className="w-full max-w-[1320px]">
              <div className="px-12 py-10">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
